#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Oct 24, 2024 12:30:55 PM CEST  platform: Linux

import requests
from noticia import noticia
#Clave API
API_KEY = 'e2aadd0618274516a3f6c5f9d1511991'
url = f'https://newsapi.org/v2/top-headlines?country=us&apiKey={API_KEY}'
noticias = []
numSeleccionado= 0


def anadirNoticias():
    try:
        response = requests.get(url)
        response.raise_for_status()  # Lanza un error si la respuesta no es exitosa
        data = response.json()
        # Verificar si hay artículos en la respuesta
        if data['articles']:
            for i in range(10):
                noticias.append(noticia(
                    titulo=data['articles'][i]['title'],
                    contenido=data['articles'][i]['content'],
                    fecha_publicacion=data['articles'][i]['publishedAt'],
                    autor=data['articles'][i]['author']
                ))  
        else:
            print('No se encontraron artículos.')
    except requests.exceptions.HTTPError as http_err:
        print(f'Error HTTP: {http_err}')
    except Exception as err:
        print(f'Ocurrió un error: {err}')


def mostrarNoticias():
    for noticia in noticias:
        print(noticia)
        saltar = input("Presiona Enter para continuar...")


def buscarNoticias():
    titulo = input("Dime el título de la noticia a buscar: ")
    for noticia in noticias:
        if titulo.lower() not in noticia.titulo.lower():
            print(f"Noticia no encontrada.")
        if titulo.lower() == noticia.titulo.lower():
            print(noticia)

def anadirNoticiasUser():
    titulo = input("Dime el título de la noticia a añadir: ")
    contenido = input("Dime el contenido de la noticia: ")
    fecha_publicacion = input("Dime la fecha de publicación: ")
    autor = input("Dime el autor de la noticia: ")

    noticias.append(noticia(
        titulo=titulo,
        contenido=contenido,
        fecha_publicacion=fecha_publicacion,
        autor=autor
    ))
    print("Noticia añadida correctamente.")

def borrarNoticias():
    titulo = input("Dime el título de la noticia a borrar: ")
    for noticia in noticias:
        if titulo.lower() not in noticia.titulo.lower():
            print(f"Noticia no encontrada.")
            
    for i in range(len(noticias)):
        
        if titulo.lower() == noticias[i].titulo.lower():
            numSeleccionado = i
            noticias.pop(numSeleccionado)
            print("Noticia borrada correctamente.")
            

def cerrar():
    print("Cerrando aplicación")
    exit()
    
def mostrarMenu():
    print("1. Mostrar Noticias")
    print("2. Buscar Noticias")
    print("3. Añadir Noticias")
    print("4. Borrar Noticias")
    print("5. Salir")
    numSeleccionado = int(input("Dime una opción: "))

    if numSeleccionado == 1:
        mostrarNoticias()
    elif numSeleccionado == 2:
        buscarNoticias()
    elif numSeleccionado == 3:
        anadirNoticiasUser()
    elif numSeleccionado == 4:
        borrarNoticias()
    elif numSeleccionado == 5:
        cerrar()
    else:
        print("Opción no válida")
        cerrar()
    
anadirNoticias()
print("1. Mostrar Noticias")
print("2. Buscar Noticias")
print("3. Añadir Noticias")
print("4. Borrar Noticias")
print("5. Salir")
numSeleccionado = int(input("Dime una opción: "))

if numSeleccionado == 1:
    mostrarNoticias()
elif numSeleccionado == 2:
    buscarNoticias()
elif numSeleccionado == 3:
    anadirNoticiasUser()
elif numSeleccionado == 4:
    borrarNoticias()
elif numSeleccionado == 5:
    cerrar()
else:
        print("Opción no válida")
        cerrar()        

while (numSeleccionado < 5 and numSeleccionado > 0):
    mostrarMenu()

